"""Test irregular-ROI prediction: zero out ref outside ROI, warp to create tar, predict.

The reference image is masked so pixels outside the ROI are black (0).
The target image is generated by warping the *masked* reference with the
ground-truth displacement field (backward mapping via scipy map_coordinates).
Both Route A and Route B are evaluated and compared.
"""
import sys; sys.path.insert(0, ".")
import argparse
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import map_coordinates

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ── helpers ──────────────────────────────────────────────────────────

def load_sample(data_dir, idx):
    """Load ref, tar, u_field, roi from dataset."""
    data_dir = Path(data_dir)
    ref = np.array(Image.open(data_dir / "ref" / f"{idx:06d}.png"), dtype=np.float32) / 255.0
    tar = np.array(Image.open(data_dir / "tar" / f"{idx:06d}.png"), dtype=np.float32) / 255.0
    u_field = np.load(data_dir / "u_field" / f"{idx:06d}.npy")            # [H, W, 2]
    roi_path = data_dir / "roi_mask" / f"{idx:06d}.png"
    if roi_path.exists():
        roi = np.array(Image.open(roi_path)) > 127
    else:
        roi = np.ones(ref.shape, dtype=bool)
    return ref, tar, u_field, roi


def warp_image(ref, u_field):
    """Warp reference image by displacement field u_field via backward mapping.

    Parameters
    ----------
    ref : np.ndarray  [H, W]
        Reference image.
    u_field : np.ndarray  [H, W, 2]
        Displacement in pixels: target pixel y corresponds to ref pixel y - u(y).

    Returns
    -------
    tar : np.ndarray  [H, W]
        Warped target image.
    """
    H, W = ref.shape
    yy, xx = np.meshgrid(np.arange(H), np.arange(W), indexing="ij")
    # backward mapping: target coordinate y -> reference coordinate y - u(y)
    src_y = yy - u_field[..., 1]
    src_x = xx - u_field[..., 0]
    coords = np.stack([src_y.ravel(), src_x.ravel()], axis=0)
    tar = map_coordinates(ref, coords, order=1, mode="constant", cval=0.0)
    return tar.reshape(H, W)


def run_prediction(route, ckpt_path, ref, tar, roi, device):
    """Run dense prediction and return metrics + displacement field."""
    import torch
    if route == "A":
        from dic_solver_operator.predict import Predictor
    else:
        from deformation_inverse_operator.predict import Predictor

    pred = Predictor(str(ckpt_path), device)
    u_pred = pred.dense(ref, tar)

    m = roi
    mae = np.abs(u_pred[m] - u_field_gt[m]).mean()
    mse = ((u_pred[m] - u_field_gt[m]) ** 2).mean()
    zero_mse = (u_field_gt[m] ** 2).mean()
    return u_pred, mae, mse, zero_mse


def make_synthetic_roi(shape, roi_type="circle", **kwargs):
    """Create a synthetic irregular ROI mask.

    Parameters
    ----------
    shape : tuple (H, W)
    roi_type : str
        "circle", "ellipse", "ring", or "notch" (plate-with-hole).

    Returns
    -------
    roi : np.ndarray [H, W] bool
    """
    H, W = shape
    yy, xx = np.meshgrid(np.arange(H), np.arange(W), indexing="ij")
    cy, cx = H / 2, W / 2

    if roi_type == "circle":
        r = kwargs.get("radius", min(H, W) * 0.35)
        roi = ((yy - cy) ** 2 + (xx - cx) ** 2) < r ** 2

    elif roi_type == "ellipse":
        rx = kwargs.get("rx", W * 0.35)
        ry = kwargs.get("ry", H * 0.25)
        roi = ((xx - cx) ** 2 / rx ** 2 + (yy - cy) ** 2 / ry ** 2) < 1

    elif roi_type == "ring":
        r_outer = kwargs.get("r_outer", min(H, W) * 0.40)
        r_inner = kwargs.get("r_inner", min(H, W) * 0.15)
        d2 = (yy - cy) ** 2 + (xx - cx) ** 2
        roi = (d2 < r_outer ** 2) & (d2 > r_inner ** 2)

    elif roi_type == "notch":
        # Dogbone / plate-with-hole shape
        margin = int(H * 0.05)
        notch_w = int(W * 0.35)
        roi = np.zeros(shape, dtype=bool)
        roi[margin:-margin, :] = True
        roi[:, :notch_w] = False
        roi[:, -notch_w:] = False
        # Add central hole
        hole_r = kwargs.get("hole_r", int(min(H, W) * 0.08))
        hole = (yy - cy) ** 2 + (xx - cx) ** 2 < hole_r ** 2
        roi = roi & ~hole

    else:
        raise ValueError(f"Unknown roi_type: {roi_type}")

    return roi


# ── plot ─────────────────────────────────────────────────────────────

def plot_all(ref_masked, tar_warped, tar_orig, roi, u_gt,
             u_a, mae_a, mse_a, zero_a, ratio_a,
             u_b, mae_b, mse_b, zero_b, ratio_b,
             idx, save_path):
    """3×4 figure: images + u_x + u_y for GT, Route A, Route B."""
    fig, axes = plt.subplots(3, 4, figsize=(20, 14))
    fig.suptitle(f"Irregular-ROI Prediction — Sample {idx:06d}", fontsize=14, fontweight="bold")

    # Row 0: images
    axes[0, 0].imshow(ref_masked, cmap="gray", vmin=0, vmax=1)
    axes[0, 0].set_title("Ref (ROI-masked)")
    axes[0, 1].imshow(tar_warped, cmap="gray", vmin=0, vmax=1)
    axes[0, 1].set_title("Tar (warped from masked ref)")
    axes[0, 2].imshow(tar_orig, cmap="gray", vmin=0, vmax=1)
    axes[0, 2].set_title("Tar (original dataset)")
    axes[0, 3].imshow(roi, cmap="gray")
    axes[0, 3].set_title(f"ROI mask ({roi.sum()} px)")

    # Rows 1-2: u_x and u_y
    mask = ~roi

    row_labels = ["u_x", "u_y"]
    for row_i, (comp_idx, label) in enumerate([(0, "u_x"), (1, "u_y")]):
        # Collect data arrays
        data_list = [
            (u_gt[..., comp_idx], f"GT {label}"),
            (u_a[..., comp_idx], f"Route A {label}\nMAE={mae_a:.3f}"),
            (u_b[..., comp_idx], f"Route B {label}\nMAE={mae_b:.3f}"),
            ((u_a - u_gt)[..., comp_idx], f"Error A-B"),
        ]
        # For u_b error in last col
        if comp_idx == 0:
            data_list[3] = ((u_a - u_gt)[..., comp_idx], f"Error A")
        else:
            data_list[3] = ((u_b - u_gt)[..., comp_idx], f"Error B")

        v = max(abs(d[~mask]).max() for d, _ in data_list[:3])
        v = max(v, 0.5)

        for col_j, (d, t) in enumerate(data_list):
            ax = axes[row_i + 1, col_j]
            d_masked = np.ma.array(d, mask=mask)
            im = ax.imshow(d_masked, cmap="RdBu_r", vmin=-v, vmax=v)
            ax.set_title(t, fontsize=10)
            plt.colorbar(im, ax=ax, shrink=0.8)

    # Row 3: error maps only, center
    for col_j in range(4):
        axes[2, col_j].axis("off")

    # Show summary text
    summary = (
        f"Route A: MAE={mae_a:.4f}  MSE={mse_a:.6f}  zero={zero_a:.6f}  ratio={ratio_a:.4f}\n"
        f"Route B: MAE={mae_b:.4f}  MSE={mse_b:.6f}  zero={zero_b:.6f}  ratio={ratio_b:.4f}"
    )
    fig.text(0.5, 0.01, summary, ha="center", fontsize=10, family="monospace")

    for ax in axes.flat[:8]:
        ax.axis("off")
    plt.tight_layout(rect=[0, 0.04, 1, 1])

    out = Path(save_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(str(out), dpi=150, bbox_inches="tight")
    print(f"Saved: {out}")
    plt.close()


# ── main ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Irregular-ROI prediction test")
    parser.add_argument("--sample", type=int, default=0)
    parser.add_argument("--data_dir", type=str, default="dataset/dataset/2026-05-27/test")
    parser.add_argument("--ckpt_a", type=str, default="checkpoints/route_a/best.pt")
    parser.add_argument("--ckpt_b", type=str, default="checkpoints/route_b/best.pt")
    parser.add_argument("--save_plot", type=str, default="predictions/irregular_roi.png")
    parser.add_argument("--roi_type", type=str, default=None,
                        choices=["circle", "ellipse", "ring", "notch"],
                        help="Override with synthetic irregular ROI (None = use dataset ROI)")
    args = parser.parse_args()

    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # 1. Load
    print(f"Loading sample {args.sample:06d} ...")
    ref_orig, tar_orig, u_field_gt_orig, roi = load_sample(args.data_dir, args.sample)
    H, W = ref_orig.shape

    # 2. Override ROI with synthetic irregular shape if requested
    if args.roi_type:
        roi = make_synthetic_roi((H, W), roi_type=args.roi_type)
        print(f"Using synthetic ROI '{args.roi_type}': {roi.sum()} pixels in ROI")

    # 3. Mask reference: zero out outside ROI
    ref_masked = ref_orig.copy()
    ref_masked[~roi] = 0.0

    # 3. Warp masked reference to generate synthetic target
    print("Warping masked reference to create synthetic target ...")
    tar_warped = warp_image(ref_masked, u_field_gt_orig)

    # Use the same GT displacement field
    global u_field_gt
    u_field_gt = u_field_gt_orig

    print(f"  ref_masked:  [{ref_masked.min():.3f}, {ref_masked.max():.3f}]")
    print(f"  tar_warped:  [{tar_warped.min():.3f}, {tar_warped.max():.3f}]")
    print(f"  tar_orig:    [{tar_orig.min():.3f}, {tar_orig.max():.3f}]")
    print(f"  u_field GT:  x=[{u_field_gt[..., 0].min():.3f}, {u_field_gt[..., 0].max():.3f}] "
          f"y=[{u_field_gt[..., 1].min():.3f}, {u_field_gt[..., 1].max():.3f}]")
    print(f"  ROI pixels:  {roi.sum()}/{roi.size}")

    # 4. Run predictions
    print(f"\nRoute A prediction ...")
    u_a, mae_a, mse_a, zero_a = run_prediction("A", args.ckpt_a, ref_masked, tar_warped, roi, device)
    ratio_a = mse_a / zero_a if zero_a > 0 else float("inf")
    print(f"  MAE={mae_a:.4f}  MSE={mse_a:.6f}  zero={zero_a:.6f}  ratio={ratio_a:.4f}")

    print(f"Route B prediction ...")
    u_b, mae_b, mse_b, zero_b = run_prediction("B", args.ckpt_b, ref_masked, tar_warped, roi, device)
    ratio_b = mse_b / zero_b if zero_b > 0 else float("inf")
    print(f"  MAE={mae_b:.4f}  MSE={mse_b:.6f}  zero={zero_b:.6f}  ratio={ratio_b:.4f}")

    # 5. Plot
    print("\nPlotting ...")
    plot_all(ref_masked, tar_warped, tar_orig, roi, u_field_gt,
             u_a, mae_a, mse_a, zero_a, ratio_a,
             u_b, mae_b, mse_b, zero_b, ratio_b,
             args.sample, args.save_plot)


if __name__ == "__main__":
    main()
